# **Numpy**
*Notas de uso para Numpy* 

**Eber Gaytán**

In [1]:
import numpy as np

## Creating Arrays

In [3]:
a = np.array([1,2,3])

In [4]:
b = np.array([(1.5,2,3),(4,5,6)], dtype = float)

In [5]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)

## Initial Placeholders

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
d = np.arange(10,25,5) #crea un array de valorers espaciados

In [10]:
e = np.full((2,2),7) #Crea un array constante

In [12]:
f = np.eye(2) #Crea una matriz identidad de 2x2

In [ ]:
np.random.random((2,2)) #Crea un array con valores random

In [14]:
 np.empty((3,2))#crea una matriz vacia

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# I/O
### Saving & Loading On Disk

In [15]:
np.save('my_array', a)

In [16]:
 np.savez('array.npz', a, b)

In [17]:
 np.load('my_array.npy')

array([1, 2, 3])

### Saving & Loading Text Files

In [21]:
np.loadtxt("myfile.txt")

FileNotFoundError: myfile.txt not found.

In [ ]:
np.genfromtxt("my_file.csv", delimiter=',' )

In [ ]:
np.savetxt("myarray.txt", a, delimiter=" " )

## Asking For Help

In [22]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Inspecting Your Array

In [23]:
a.shape #Dimension de la matriz a

(3,)

In [24]:
len(a) #longitud de la matreiz

3

In [25]:
b.ndim #Numero de dimensiones

2

In [26]:
 e.size # numero de elementos de la matriz

4

In [27]:
 b.dtype # Tipo de dato en la matriz

dtype('float64')

In [28]:
b.dtype.name # Nombre del tipo de dato

'float64'

In [30]:
b.astype(int) #Convertir Array en diferente tipo

array([[1, 2, 3],
       [4, 5, 6]])

 # Data Types

In [31]:
np.int64 #Signed 64-bit integer types

numpy.int64

In [32]:
np.float32 #Standard double-precision floating point

numpy.float32

In [ ]:
np.complex #Complex numbers represented by 128 floats

In [ ]:
np.bool #Boolean type storing TRUE and FALSE values

In [ ]:
np.object #Python object type

In [ ]:
np.string_ #Fixed-length string type

In [ ]:
np.unicode_ #Fixed-length unicode type

# Array Mathematics
### Arithmetic Operations

In [ ]:
 g = a - b #Subtraction

In [33]:
 np.subtract(a,b) #Subtractio

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [34]:
 b + a  #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [35]:
 np.add(b,a) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
 a / b #Division

In [ ]:
np.divide(a,b) #Division

In [ ]:
 a * b #Multiplicacion

In [ ]:
 np.multiply(a,b) #Multiplicacion

In [ ]:
np.exp(b) #Exponenciacion

In [ ]:
np.sqrt(b) #Raiz cuadrada

In [ ]:
 np.sin(a) #Imprime los senos de un array

In [ ]:
 np.cos(b) #Imprime los cosenos de un array

In [37]:
np.log(a) #Imprime los logaritmos naturales de la matriz

array([0.        , 0.69314718, 1.09861229])

In [38]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

# Comparison

In [39]:
 a == b #Comparacion de dos elementos

array([[False,  True,  True],
       [False, False, False]])

In [40]:
a < 2 #A menor que 2

array([ True, False, False])

In [42]:
 np.array_equal(a, b) #Compara si el array es igual al otro array

False

# Aggregate Functions

In [47]:
a.sum() #suma todo el array

6

In [48]:
a.min() #Busca el valor minimo

1

In [49]:
b.max(axis=0) #Maximo valor del renglon 0

array([4., 5., 6.])

In [50]:
 b.cumsum(axis=1) #Suma de elementos acumulacion

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [52]:
 a.mean() #Que es mean?

2.0

In [54]:
np.median(b) #La mediana de B

3.5

In [55]:
np.corrcoef(a) #Correlacion de coeficientes

1.0

In [56]:
np.std(b) #Desviacion Standar

1.5920810978785667

#  Copying Arrays

In [57]:
h = a.view() #Crea la vista de un arrar con la misma informacion

In [58]:
np.copy(a) #Crea una copia del array

array([1, 2, 3])

In [59]:
h=a.copy() #Crea una copia profunda

In [60]:
print(h)

[1 2 3]
